/**
 * NotesSearchResults — Dedicated search results page
 *
 * Rendered at `/notes/search?q=...` inside the Notes workspace for long
 * result sets. Reads the query from the URL, runs a full search on mount,
 * and lists results with breadcrumbs. Links are also generated by the command
 * palette's "View all" action.
 *
 * @module @frontend/pages/NotesSearchResults
 */

import React, { useEffect } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';

import { SearchResultItem } from '../components/notes/SearchResultItem';
import { usePageSearch } from '../hooks/usePageSearch';
import './NotesSearchResults.css';

export function NotesSearchResults(): JSX.Element {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const query = searchParams.get('q') ?? '';

  const {
    query: currentQuery,
    results,
    isSearching,
    error,
    setQuery,
    runSearch,
    loadCatalog,
    breadcrumbsOf,
  } = usePageSearch(50);

  useEffect(() => {
    void loadCatalog();
  }, [loadCatalog]);

  useEffect(() => {
    setQuery(query);
    if (query.trim()) {
      void runSearch(query.trim());
    }
  }, [query, setQuery, runSearch]);

  const hasQuery = currentQuery.trim() !== '';
  const showNoResults = hasQuery && !isSearching && results.length === 0 && !error;

  return (
    <div className="notes-search-results">
      <header className="notes-search-results__header">
        <div className="notes-search-results__title-row">
          <Link to="/notes" className="notes-search-results__back">
            ← Notes
          </Link>
          <h1 className="notes-search-results__title">Search results</h1>
        </div>
        <p className="notes-search-results__query">
          {hasQuery ? `Results for “${query}”` : 'Type a query to search pages.'}
        </p>
      </header>

      {isSearching && <p className="notes-search-results__status">Searching…</p>}

      {!isSearching && error && (
        <p className="notes-search-results__empty notes-search-results__empty--error">{error}</p>
      )}

      {!isSearching && showNoResults && (
        <div className="notes-search-results__empty">
          <p>No pages found for “{query}”.</p>
          <Link to="/notes" className="notes-search-results__cta">
            Return to Notes
          </Link>
        </div>
      )}

      {!isSearching && !error && results.length > 0 && (
        <ul role="listbox" aria-label="Search results" className="notes-search-results__list">
          {results.map((result, index) => (
            <SearchResultItem
              key={result.page.id}
              page={result.page}
              snippet={result.snippet}
              query={query}
              breadcrumbs={breadcrumbsOf(result.page)}
              selected={false}
              id={`notes-search-result-${index}`}
              onSelect={() => {
                void navigate(`/notes/${result.page.id}`);
              }}
            />
          ))}
        </ul>
      )}
    </div>
  );
}