/**
 * Database Mappers — Pure Functions
 *
 * Type-safe conversions between database rows (snake_case) and domain objects (camelCase).
 * Zero dependencies — no I/O, no Electron, no Node. Safe to import in any environment.
 *
 * @module @backend/main/db/mappers
 */

import type {
  Assignment,
  AssignmentInput,
  SubTask,
  SubTaskInput,
  Note,
  NoteInput,
  Page,
  PageInput,
  PageUpdateInput,
  PriorityOrder,
  PriorityOrderInput,
  Settings,
  DbAssignment,
  DbSubTask,
  DbNote,
  DbPage,
  DbPriorityOrder,
  DbSettings,
  IsoDateTime,
} from '../../shared/types.js';

/**
 * Convert Unix milliseconds to ISO 8601 UTC string.
 */
export function toIsoDateTime(ms: number): string {
  return new Date(ms).toISOString();
}

/**
 * Convert ISO 8601 string to Unix milliseconds (or null).
 */
export function toUnixMs(iso: string | null | undefined): number | null {
  if (!iso) return null;
  return new Date(iso).getTime();
}

/**
 * Map database row to Assignment domain object.
 */
export function mapDbAssignmentToAssignment(row: DbAssignment): Assignment {
  return {
    id: row.id as Assignment['id'],
    title: row.title,
    description: row.description ?? '',
    courseId: row.course_name as Assignment['courseId'],
    courseName: row.course_name,
    courseColor: row.course_color ?? '#6366f1',
    dueAt: row.due_at ? (toIsoDateTime(row.due_at) as IsoDateTime) : null,
    unlockAt: row.unlock_at ? (toIsoDateTime(row.unlock_at) as IsoDateTime) : null,
    lockAt: row.lock_at ? (toIsoDateTime(row.lock_at) as IsoDateTime) : null,
    pointsPossible: row.points_possible ?? null,
    submissionTypes: row.submission_types ? JSON.parse(row.submission_types) : [],
    workflowState: row.workflow_state ?? 'published',
    htmlUrl: row.html_url ?? '',
    icalUid: row.ical_uid ?? '',
    // priority is calculated, not stored in DB
    priority: 'low',
    status: (row.status as Assignment['status']) ?? 'pending',
    source: (row.source as Assignment['source']) ?? 'manual',
    sourceUrl: row.source_url ?? undefined,
    rrule: row.rrule ?? undefined,
    createdAt: toIsoDateTime(row.created_at) as Assignment['createdAt'],
    updatedAt: toIsoDateTime(row.updated_at) as Assignment['updatedAt'],
  };
}

/**
 * Map AssignmentInput to database row format for upsert.
 * Only includes fields that are defined in the input.
 */
export function mapAssignmentInputToDb(input: AssignmentInput, now: number): Partial<DbAssignment> {
  const dbRow: Partial<DbAssignment> = {};

  if (input.id !== undefined) dbRow.id = input.id;
  if (input.title !== undefined) dbRow.title = input.title;
  if (input.description !== undefined) dbRow.description = input.description;
  if (input.courseId !== undefined) dbRow.canvas_id = input.courseId;
  if (input.courseName !== undefined) dbRow.course_name = input.courseName;
  if (input.courseColor !== undefined) dbRow.course_color = input.courseColor;
  if (input.dueAt !== undefined) dbRow.due_at = toUnixMs(input.dueAt) ?? now;
  if (input.unlockAt !== undefined) dbRow.unlock_at = toUnixMs(input.unlockAt);
  if (input.lockAt !== undefined) dbRow.lock_at = toUnixMs(input.lockAt);
  if (input.pointsPossible !== undefined) dbRow.points_possible = input.pointsPossible;
  if (input.submissionTypes !== undefined)
    dbRow.submission_types = JSON.stringify(input.submissionTypes);
  if (input.workflowState !== undefined) dbRow.workflow_state = input.workflowState;
  if (input.htmlUrl !== undefined) dbRow.html_url = input.htmlUrl;
  if (input.icalUid !== undefined) dbRow.ical_uid = input.icalUid;
  // priority is calculated, not stored in DB — skip
  if (input.status !== undefined) dbRow.status = input.status;
  if (input.source !== undefined) dbRow.source = input.source;
  if (input.sourceUrl !== undefined) dbRow.source_url = input.sourceUrl;
  if (input.rrule !== undefined) dbRow.rrule = input.rrule;
  if (input.createdAt !== undefined) dbRow.created_at = toUnixMs(input.createdAt) ?? now;
  if (input.updatedAt !== undefined) dbRow.updated_at = toUnixMs(input.updatedAt) ?? now;

  return dbRow;
}

export function mapDbSubTaskToSubTask(row: DbSubTask): SubTask {
  return {
    id: row.id as SubTask['id'],
    assignmentId: row.assignment_id as SubTask['assignmentId'],
    title: row.title,
    completed: row.completed === 1,
    order: row.position,
    createdAt: toIsoDateTime(row.created_at) as SubTask['createdAt'],
    updatedAt: toIsoDateTime(row.updated_at) as SubTask['updatedAt'],
  };
}

export function mapSubTaskInputToDb(input: SubTaskInput, now: number): DbSubTask {
  return {
    id: '', // Will be generated by repository
    assignment_id: input.assignmentId,
    title: input.title,
    completed: input.completed ? 1 : 0,
    position: input.order,
    created_at: now,
    updated_at: now,
  };
}

export function mapDbSettingsToSettings(rows: DbSettings[]): Settings {
  const defaults: Settings = {
    theme: 'system',
    autoFetchIcal: false,
    icalFetchIntervalMinutes: 60,
    defaultPriority: 'medium',
    showCompletedAssignments: true,
    notifyDueSoon: true,
    dueSoonThresholdHours: 24,
    icalUrl: '',
    lastSyncAt: null,
    autoFetchIntervalMs: 60 * 60 * 1000, // 60 minutes in ms
    syncIntervalMinutes: 15,
  };

  const result = { ...defaults };
  for (const row of rows) {
    try {
      const value = JSON.parse(row.value);
      // Type-safe assignment - we trust the stored JSON matches Settings structure
      (result as Record<string, unknown>)[row.key] = value;
    } catch {
      // Ignore invalid JSON, keep default
    }
  }
  // Compute autoFetchIntervalMs from icalFetchIntervalMinutes
  result.autoFetchIntervalMs = result.icalFetchIntervalMinutes * 60 * 1000;
  return result;
}

/**
 * Map database row to PriorityOrder domain object.
 */
export function mapDbPriorityOrderToPriorityOrder(row: DbPriorityOrder): PriorityOrder {
  return {
    id: row.assignment_id as PriorityOrder['id'],
    assignmentId: row.assignment_id as PriorityOrder['assignmentId'],
    order: row.position,
    updatedAt: toIsoDateTime(row.updated_at) as PriorityOrder['updatedAt'],
  };
}

/**
 * Map database row to PriorityOrder domain object (alias for repository layer).
 */
export function mapPriorityOrderRow(row: DbPriorityOrder): PriorityOrder {
  return mapDbPriorityOrderToPriorityOrder(row);
}

/**
 * Validate and map PriorityOrderInput to database row format for upsert.
 * Generates timestamps for new records.
 */
export function mapPriorityOrderInputToDb(
  input: PriorityOrderInput,
  now: number = Date.now(),
): DbPriorityOrder {
  return {
    assignment_id: input.assignmentId,
    position: input.order,
    created_at: now,
    updated_at: now,
  };
}

/**
 * Map database row to Note domain object (1:N model: multiple notes per assignment).
 */
export function mapDbNoteToNote(row: DbNote): Note {
  return {
    id: row.id as Note['id'],
    assignmentId: row.assignment_id as Note['assignmentId'],
    content: row.content,
    createdAt: toIsoDateTime(row.created_at) as Note['createdAt'],
    updatedAt: toIsoDateTime(row.updated_at) as Note['updatedAt'],
  };
}

/**
 * Map NoteInput to database row format for insert.
 * Generates timestamps for new records.
 */
export function mapNoteInputToDb(input: NoteInput, now: number): DbNote {
  return {
    id: '', // Will be generated by repository
    assignment_id: input.assignmentId,
    content: input.content,
    created_at: now,
    updated_at: now,
  };
}

/**
 * Map database row to Page domain object.
 */
export function mapDbPageToPage(row: DbPage): Page {
  return {
    id: row.id as Page['id'],
    parentId: row.parent_id as Page['parentId'],
    title: row.title,
    content: row.content,
    icon: row.icon,
    cover: row.cover,
    position: row.position,
    createdAt: toIsoDateTime(row.created_at) as Page['createdAt'],
    updatedAt: toIsoDateTime(row.updated_at) as Page['updatedAt'],
    createdBy: row.created_by,
  };
}

/**
 * Map PageInput to database row format for insert.
 * Generates timestamps for new records.
 */
export function mapPageInputToDb(input: PageInput, now: number): DbPage {
  return {
    id: '', // Will be generated by repository
    parent_id: input.parentId ?? null,
    title: input.title,
    content: input.content ?? null,
    icon: input.icon ?? null,
    cover: input.cover ?? null,
    position: input.position ?? 0,
    created_at: now,
    updated_at: now,
    created_by: null, // Will be set by repository if needed
  };
}

/**
 * Map PageUpdateInput to database row format for update.
 * Only includes fields that are defined in the input.
 */
export function mapPageUpdateInputToDb(input: PageUpdateInput, now: number): Partial<DbPage> {
  const dbRow: Partial<DbPage> = {};

  if (input.title !== undefined) dbRow.title = input.title;
  if (input.content !== undefined) dbRow.content = input.content;
  if (input.parentId !== undefined) dbRow.parent_id = input.parentId;
  if (input.position !== undefined) dbRow.position = input.position;
  if (input.icon !== undefined) dbRow.icon = input.icon;
  if (input.cover !== undefined) dbRow.cover = input.cover;
  dbRow.updated_at = now;

  return dbRow;
}
