/**
 * Database Mappers — Pure Functions
 *
 * Type-safe conversions between database rows (snake_case) and domain objects (camelCase).
 * Zero dependencies — no I/O, no Electron, no Node. Safe to import in any environment.
 *
 * @module @backend/main/db/mappers
 */

import type {
  Assignment,
  AssignmentInput,
  SubTask,
  SubTaskInput,
  Note,
  PriorityOrder,
  PriorityOrderInput,
  Settings,
  DbAssignment,
  DbSubTask,
  DbSettings,
  IsoDateTime,
  EntityId,
} from '../../shared/types.js';

/**
 * Convert Unix milliseconds to ISO 8601 UTC string.
 */
export function toIsoDateTime(ms: number): string {
  return new Date(ms).toISOString();
}

/**
 * Convert ISO 8601 string to Unix milliseconds (or null).
 */
export function toUnixMs(iso: string | null | undefined): number | null {
  if (!iso) return null;
  return new Date(iso).getTime();
}

/**
 * Map database row to Assignment domain object.
 */
export function mapDbAssignmentToAssignment(row: DbAssignment): Assignment {
  return {
    id: row.id as Assignment['id'],
    title: row.title,
    description: row.description ?? '',
    courseId: row.course_name as Assignment['courseId'],
    courseName: row.course_name,
    courseColor: row.course_color ?? '#6366f1',
    dueAt: row.due_at ? (toIsoDateTime(row.due_at) as IsoDateTime) : null,
    unlockAt: row.unlock_at ? (toIsoDateTime(row.unlock_at) as IsoDateTime) : null,
    lockAt: row.lock_at ? (toIsoDateTime(row.lock_at) as IsoDateTime) : null,
    pointsPossible: row.points_possible ?? null,
    submissionTypes: row.submission_types ? JSON.parse(row.submission_types) : [],
    workflowState: row.workflow_state ?? 'published',
    htmlUrl: row.html_url ?? '',
    icalUid: row.ical_uid ?? '',
    // priority is calculated, not stored in DB
    priority: 'low' as Assignment['priority'],
    status: (row.status as Assignment['status']) ?? 'pending',
    source: (row.source as Assignment['source']) ?? 'manual',
    sourceUrl: row.source_url ?? undefined,
    rrule: row.rrule ?? undefined,
    createdAt: toIsoDateTime(row.created_at) as Assignment['createdAt'],
    updatedAt: toIsoDateTime(row.updated_at) as Assignment['updatedAt'],
  };
}

/**
 * Map AssignmentInput to database row format for upsert.
 * Only includes fields that are defined in the input.
 */
export function mapAssignmentInputToDb(input: AssignmentInput, now: number): Partial<DbAssignment> {
  const dbRow: Partial<DbAssignment> = {};

  if (input.id !== undefined) dbRow.id = input.id;
  if (input.title !== undefined) dbRow.title = input.title;
  if (input.description !== undefined) dbRow.description = input.description;
  if (input.courseId !== undefined) dbRow.canvas_id = input.courseId;
  if (input.courseName !== undefined) dbRow.course_name = input.courseName;
  if (input.courseColor !== undefined) dbRow.course_color = input.courseColor;
  if (input.dueAt !== undefined) dbRow.due_at = toUnixMs(input.dueAt) ?? now;
  if (input.unlockAt !== undefined) dbRow.unlock_at = toUnixMs(input.unlockAt);
  if (input.lockAt !== undefined) dbRow.lock_at = toUnixMs(input.lockAt);
  if (input.pointsPossible !== undefined) dbRow.points_possible = input.pointsPossible;
  if (input.submissionTypes !== undefined) dbRow.submission_types = JSON.stringify(input.submissionTypes);
  if (input.workflowState !== undefined) dbRow.workflow_state = input.workflowState;
  if (input.htmlUrl !== undefined) dbRow.html_url = input.htmlUrl;
  if (input.icalUid !== undefined) dbRow.ical_uid = input.icalUid;
  // priority is calculated, not stored in DB — skip
  if (input.status !== undefined) dbRow.status = input.status;
  if (input.source !== undefined) dbRow.source = input.source;
  if (input.sourceUrl !== undefined) dbRow.source_url = input.sourceUrl;
  if (input.rrule !== undefined) dbRow.rrule = input.rrule;
  if (input.createdAt !== undefined) dbRow.created_at = toUnixMs(input.createdAt) ?? now;
  if (input.updatedAt !== undefined) dbRow.updated_at = toUnixMs(input.updatedAt) ?? now;

  return dbRow;
}

export function mapDbSubTaskToSubTask(row: DbSubTask): SubTask {
  return {
    id: row.id as SubTask['id'],
    assignmentId: row.assignment_id as SubTask['assignmentId'],
    title: row.title,
    completed: row.completed === 1,
    order: row.position,
    createdAt: toIsoDateTime(row.created_at) as SubTask['createdAt'],
    updatedAt: toIsoDateTime(row.updated_at) as SubTask['updatedAt'],
  };
}

export function mapSubTaskInputToDb(input: SubTaskInput, now: number): DbSubTask {
  return {
    id: '' as SubTask['id'], // Will be generated by repository
    assignment_id: input.assignmentId,
    title: input.title,
    completed: input.completed ? 1 : 0,
    position: input.order,
    created_at: now,
    updated_at: now,
  };
}

export function mapDbSettingsToSettings(rows: DbSettings[]): Settings {
  const defaults: Settings = {
    theme: 'system',
    autoFetchIcal: false,
    icalFetchIntervalMinutes: 60,
    defaultPriority: 'medium',
    showCompletedAssignments: true,
    notifyDueSoon: true,
    dueSoonThresholdHours: 24,
    icalUrl: '',
    lastSyncAt: null,
    autoFetchIntervalMs: 60 * 60 * 1000, // 60 minutes in ms
  };

  const result = { ...defaults };
  for (const row of rows) {
    try {
      const value = JSON.parse(row.value);
      // Type-safe assignment - we trust the stored JSON matches Settings structure
      (result as Record<string, unknown>)[row.key] = value;
    } catch {
      // Ignore invalid JSON, keep default
    }
  }
  // Compute autoFetchIntervalMs from icalFetchIntervalMinutes
  result.autoFetchIntervalMs = result.icalFetchIntervalMinutes * 60 * 1000;
  return result;
}