/**
 * Core Domain Types
 *
 * Pure TypeScript — zero Electron/Node dependencies.
 * Used across Main, Preload, and Renderer via project references.
 *
 * @module @backend/shared/types
 */

/**
 * Unique identifier (UUID v4 string).
 */
export type EntityId = string & { readonly __brand: unique symbol };

/**
 * ISO 8601 date-time string.
 */
export type IsoDateTime = string & { readonly __brand: unique symbol };

/**
 * Assignment — core entity representing a course task.
 */
export interface Assignment {
  id: EntityId;
  title: string;
  description: string;
  courseId: EntityId | null;
  dueDate: IsoDateTime | null;
  priority: number; // lower = higher priority
  status: AssignmentStatus;
  source: AssignmentSource;
  sourceUrl: string | null; // iCal UID or URL if imported
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

/**
 * Input for creating/updating an assignment.
 * Omit id, createdAt, updatedAt (generated by DB).
 */
export interface AssignmentInput {
  title: string;
  description: string;
  courseId: EntityId | null;
  dueDate: IsoDateTime | null;
  priority: number;
  status: AssignmentStatus;
  source: AssignmentSource;
  sourceUrl: string | null;
}

export type AssignmentStatus = 'pending' | 'in_progress' | 'completed' | 'archived';

export type AssignmentSource = 'manual' | 'ical';

/**
 * SubTask — atomic unit of work within an assignment.
 */
export interface SubTask {
  id: EntityId;
  assignmentId: EntityId;
  title: string;
  completed: boolean;
  order: number;
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

export interface SubTaskInput {
  assignmentId: EntityId;
  title: string;
  completed: boolean;
  order: number;
}

/**
 * Note — free-form text attached to an assignment.
 */
export interface Note {
  id: EntityId;
  assignmentId: EntityId;
  content: string; // Markdown
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

export interface NoteInput {
  assignmentId: EntityId;
  content: string;
}

/**
 * PriorityOrder — explicit ordering of assignments for drag-drop priority.
 * Separate from Assignment.priority to allow arbitrary reordering.
 */
export interface PriorityOrder {
  id: EntityId; // same as assignmentId
  assignmentId: EntityId;
  order: number; // 0 = highest priority
  updatedAt: IsoDateTime;
}

export interface PriorityOrderInput {
  assignmentId: EntityId;
  order: number;
}

/**
 * User Settings — persisted in DB, synced via IPC.
 */
export interface Settings {
  theme: 'light' | 'dark' | 'system';
  autoFetchIcal: boolean;
  icalFetchIntervalMinutes: number;
  defaultPriority: number;
  showCompletedAssignments: boolean;
  notifyDueSoon: boolean;
  dueSoonThresholdHours: number;
}

/**
 * iCal Event — parsed from iCal feed, used for import preview.
 */
export interface ICalEvent {
  uid: string;
  summary: string;
  description: string | null;
  location: string | null;
  dtStart: IsoDateTime;
  dtEnd: IsoDateTime | null;
  rrule: string | null; // RFC 5545 recurrence rule
  url: string | null;
  categories: string[]; // e.g., ['CS101', 'Homework']
}

/**
 * Course — optional grouping for assignments (future use).
 */
export interface Course {
  id: EntityId;
  name: string;
  code: string; // e.g., "CS101"
  color: string; // hex color
  term: string; // e.g., "Fall 2025"
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

export interface CourseInput {
  name: string;
  code: string;
  color: string;
  term: string;
}

/**
 * Database row types (snake_case for SQL compatibility).
 * Internal to Main process — not exposed via IPC.
 */
export interface DbAssignment {
  id: string;
  canvas_id: string | null;
  title: string;
  description: string | null;
  course_name: string;
  course_color: string | null;
  due_at: number;
  unlock_at: number | null;
  lock_at: number | null;
  points_possible: number | null;
  submission_types: string | null;
  workflow_state: string | null;
  html_url: string | null;
  ical_uid: string | null;
  created_at: number;
  updated_at: number;
}

export interface DbSubTask {
  id: string;
  assignment_id: string;
  title: string;
  completed: number; // 0/1
  position: number;
  created_at: number;
  updated_at: number;
}

export interface DbNote {
  assignment_id: string;
  content: string;
  updated_at: number;
}

export interface DbPriorityOrder {
  assignment_id: string;
  position: number;
}

export interface DbSettings {
  key: string;
  value: string; // JSON stringified
}

export interface DbCourse {
  id: string;
  name: string;
  code: string;
  color: string;
  term: string;
  created_at: string;
  updated_at: string;
}

/**
 * Type guards for runtime validation (used in Main handlers).
 */
export function isValidAssignment(input: unknown): input is AssignmentInput {
  if (!input || typeof input !== 'object') return false;
  const obj = input as Record<string, unknown>;
  return (
    typeof obj['title'] === 'string' &&
    typeof obj['description'] === 'string' &&
    (obj['courseId'] === null || typeof obj['courseId'] === 'string') &&
    (obj['dueDate'] === null || typeof obj['dueDate'] === 'string') &&
    typeof obj['priority'] === 'number' &&
    ['pending', 'in_progress', 'completed', 'archived'].includes(obj['status'] as string) &&
    ['manual', 'ical'].includes(obj['source'] as string) &&
    (obj['sourceUrl'] === null || typeof obj['sourceUrl'] === 'string')
  );
}

export function isValidSubTaskInput(input: unknown): input is SubTaskInput {
  if (!input || typeof input !== 'object') return false;
  const obj = input as Record<string, unknown>;
  return (
    typeof obj['assignmentId'] === 'string' &&
    typeof obj['title'] === 'string' &&
    typeof obj['completed'] === 'boolean' &&
    typeof obj['order'] === 'number'
  );
}

export function isValidNoteInput(input: unknown): input is NoteInput {
  if (!input || typeof input !== 'object') return false;
  const obj = input as Record<string, unknown>;
  return typeof obj['assignmentId'] === 'string' && typeof obj['content'] === 'string';
}

export function isValidPriorityOrderInput(input: unknown): input is PriorityOrderInput {
  if (!input || typeof input !== 'object') return false;
  const obj = input as Record<string, unknown>;
  return typeof obj['assignmentId'] === 'string' && typeof obj['order'] === 'number';
}

export function isValidSettings(input: unknown): input is Partial<Settings> {
  if (!input || typeof input !== 'object') return false;
  const obj = input as Record<string, unknown>;
  return (
    (obj['theme'] === undefined || ['light', 'dark', 'system'].includes(obj['theme'] as string)) &&
    (obj['autoFetchIcal'] === undefined || typeof obj['autoFetchIcal'] === 'boolean') &&
    (obj['icalFetchIntervalMinutes'] === undefined ||
      typeof obj['icalFetchIntervalMinutes'] === 'number') &&
    (obj['defaultPriority'] === undefined || typeof obj['defaultPriority'] === 'number') &&
    (obj['showCompletedAssignments'] === undefined ||
      typeof obj['showCompletedAssignments'] === 'boolean') &&
    (obj['notifyDueSoon'] === undefined || typeof obj['notifyDueSoon'] === 'boolean') &&
    (obj['dueSoonThresholdHours'] === undefined || typeof obj['dueSoonThresholdHours'] === 'number')
  );
}
